repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: b965c2a5026f8ba399283ba3e01898b012853c79  # 24.2.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2e14b23f8a70c503b6e3f7f4ac8a4b98e8a8e5c0  # v0.3.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
